### ISSUE TITLE
MLMainWindow doesn't included in Windows menu

### ISSUE THREAD

**Issue by gyetvan-andras** [gyetvan-andras/ModernLook-OSX#2]
MLMainWindow should be included in the app's Window menu. At this point I don't know is it because MLWindow does not have a real title or has a style of NSBorderlessWindowMask. Needs more investigation.

**Comment by joemcbride** [comment]
Nice looking project - hope this helps! [Docs on using Windows Menu](https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/WinPanel/Tasks/UsingWindowsMenu.html)

**Comment by gyetvan-andras** [comment]
Thanks, that helped a lot. That was the key: - (void)addWindowsItem:(NSWindow *)aWindow title:(NSString *)aString filename:(BOOL)isFilename
