### ISSUE TITLE
vertical buttons

### ISSUE THREAD

**Issue by trondkr** [gyetvan-andras/ModernLook-OSX#4]
Hi. Thanks for a great toolbox! I just have a minor issue. In MLToolBar.m I have to manually call `setVerticalButtons`:

```
- (instancetype)initWithFrame: (NSRect)frameRect
{
     if(frameRect.size.height > 20) {
         _verticalButtons = YES;
    } else {
        _verticalButtons = NO;
    }   
    self = [super initWithFrame: frameRect];
    [self setVerticalButtons:_verticalButtons];
return self;
}
```

for buttons to become vertical, otherwise they will be horizontal.Cheers, Trond

**Comment by gyetvan-andras** [comment]
Thanks a lot to pointing out. I did not realize this problem, because my test code contains setting in IB for verticalButtons property and I've forgotten to fix automatic (height based) button layout.

**Comment by gyetvan-andras** [comment]
The fix is committed.
