### ISSUE TITLE
swift version it 's not finish

### ISSUE THREAD

**Issue by thierryH91200** [gyetvan-andras/ModernLook-OSX#8]
[ModernLookOSXSampleSwift.zip](https://github.com/gyetvan-andras/ModernLook-OSX/files/3103513/ModernLookOSXSampleSwift.zip)

**Comment by thierryH91200** [comment]
[ModernLookOSXSampleSwift.zip](https://github.com/gyetvan-andras/ModernLook-OSX/files/3103511/ModernLookOSXSampleSwift.zip)

**Comment by gyetvan-andras** [comment]
It looks good, but what you expect from me?  I suggest to create a new repo for this, then I can extend the description adding a link and stating that there is a Swift version maintained by you.

**Comment by thierryH91200** [comment]
ok I agree

**Comment by thierryH91200** [comment]
here is the link

under construction

[https://github.com/thierryH91200/ModernLookOSXSampleSwift](url)

**Comment by gyetvan-andras** [comment]
Thanks, README updated.
